server:
  port: 8005

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: b3
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

spring:
  profiles:
    active: local
  application:
    name: stock-notification-service
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/analytics
    username: admin
    password: 123456
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/analytics
    baseline-on-migrate: true
    repair-on-migrate: true
  netty:
    leak-detection: paranoid
  kafka:
    topic: "session-state-update-events"
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: analytics-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        auto.offset.reset: latest
        max.poll.records: 200


logging:
  level:
    inc.evil: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
    org.zalando.logbook: trace
